### ISSUE TITLE
format() function is not showing correct timezone

### ISSUE THREAD

**Issue by Sparkenstein** [xx45/dayjs#105]
According to docs at [github](https://github.com/xx45/dayjs#format), the function `dayjs().format()` (without any arguments) should return a timestamp with timezone like "2018-05-06T14:31:02+05:30" (My timezone is +5:30). But instead it's returning "2018-05-06T14:31:020500:00". I checked with the code, even test for `Format no formatStr` is failing with : 
```Format no formatStr

    expect(received).toBe(expected) // Object.is equality

    Expected value to be:
      "2018-05-06T14:26:00+05:30"
    Received:
      "2018-05-06T14:26:000500:00"
```

**Comment by Imperat** [comment]
Hi, @Sparkenstein. I open pull request to fix this bug.
+5:30 is to interesting timezone. Where are you from? :)

**Comment by Imperat** [comment]
Hi, @iamkun. Can you review my PR, please?)

**Comment by iamkun** [comment]
@Imperat @Sparkenstein 
Thanks. +5:30 time zone is fresh to me.

**Comment by itsashis4u** [comment]
@Imperat +5:30 is India's Timezone primarily :)
