### ISSUE TITLE
parse month day without leading zero cause Invalid Date  2018-05-07 解析月日有前导零的字符串显示为

### ISSUE THREAD

**Issue by iamziyue** [xx45/dayjs#112]
版本：1.5.20
当月和日无前导零或者本来就是两位数时没问题，个位数的月或日加上前导零时解析出错。
在线演示：http://runjs.cn/code/d3c2uzex

另外作者能否加个更新日志呢，想知道每次更新了些什么。

**Comment by iamkun** [comment]
Thanks. Will check this.

You could check our release notes at [https://github.com/xx45/dayjs/releases](https://github.com/xx45/dayjs/releases)

However, change log is needed I think.
