### ISSUE TITLE
using add() with string amount when adding years appends string instead of adds

### ISSUE THREAD

**Issue by ljmerza** [xx45/dayjs#115]
```
dayjs('2018-01-20 10:00:00').add('2', 'years')
```

expected output is 

```
Sun Jan 20 2020 10:00:00 GMT-0500
```

but instead get 

```
Sun Jan 20 20182 10:00:00 GMT-0500
```

if we use an integer then the output is correct. Using a string as the amount for days, hours, etc unit works just fine

**Comment by iamkun** [comment]
Well, we use `year + userInput` here, so results 20182 

Just don't understand why passing a string rather than a number here? 😁
