### ISSUE TITLE
Improvements on the introduction.

### ISSUE THREAD

**Issue by AlvinTheDeveloper** [xx45/dayjs#135]
For the introduction in README.md I think we should mention what day.js can do. Shouldn't wait for the user scroll to the API reference and spend some time to understand what is going on.

I think we should add some introduction about the functions right before the sentence below:

> Day.js is a minimalist JavaScript library for modern browsers with a largely Moment.js-compatible API. If you use Moment.js, you already know how to use Day.js.

**Comment by iamkun** [comment]
Umm, maybe a website is needed at this moment.

Or any suggestion to our readme structure?

**Comment by dmckenna24** [comment]
I agree with @iamkun, I've previously worked on moment, and having the website with all required documentation and introductory information was useful before entering their GitHub. Perhaps create an issue on this? Or is it too big of a scale for just a regular issue?

**Comment by iamkun** [comment]
@dmckenna24 agreed!

**Comment by iamkun** [comment]
@AlvinTheDeveloper THX, that make sense.

**Comment by iamkun** [comment]
@AlvinTheDeveloper added to readme, better?

**Comment by AlvinTheDeveloper** [comment]
Will do. I was busying. Sorry about that.

**Comment by AlvinTheDeveloper** [comment]
Sorry I have just found some grammatical mistakes in my sentence.
This should be better:

> Day.js is a minimalist JavaScript library that parses, validates, manipulates, and displays dates and times for modern browsers with a largely Moment.js-compatible API. If you use Moment.js, you already know how to use Day.js.

**Comment by iamkun** [comment]
@AlvinTheDeveloper THX, I'll update it to readme.

**Comment by iamkun** [comment]
Doc updated!
