### ISSUE TITLE
ability to parse using custom format, like in format function.

### ISSUE THREAD

**Issue by mnewmedia** [xx45/dayjs#137]
Just what keeps me away from using this -> ability to parse using custom format, like in format function.

Same issue in date-fns but will work in the upcoming 2.0 release of date-fns. https://github.com/date-fns/date-fns/issues/219

But cool lib, thanks for sharing!

**Comment by iamkun** [comment]
same issue #136 ?

**Comment by mnewmedia** [comment]
@iamkun yep, how could i not see this 😆. sorry.
