### ISSUE TITLE
dayjs init data seems not right

### ISSUE THREAD

**Issue by YikaJ** [xx45/dayjs#138]
When I init data like this, not like `moment.js` can make right way to parse the Date String.

```
console.log(dayjs('2018-01'))

output:
Fri Dec 01 2017 00:00:00 GMT+0800 (CST
```

But I can solve by pass the Date, and init with `new Date(string)`.

```
console.log(dayjs(new Date('2018-01')))

output:
Mon Jan 01 2018 08:00:00 GMT+0800 (CST)
```

希望你能看得懂...

**Comment by iamkun** [comment]
It's a bug. However, maybe dayjs('2018-01-01') would be better? 

'2018-01' could either be '2018-01-01' or '2018-01-31'
