### ISSUE TITLE
Parse minute only 转化分钟 

### ISSUE THREAD

**Issue by LPmagic** [xx45/dayjs#38]
Moment('20:15') =>ok
dayjs('20:15') =>Invalid Date

**Comment by loo41** [comment]
const parseConfig = (config) => {
  if (!config) return new Date()
  if (config instanceof Date) return config
  const configStr = String(config)
  if (/^(\d){8}$/.test(configStr)) {
    const y = configStr.substr(0, 4)
    const m = configStr.substr(4, 2)
    const d = configStr.substr(6, 2)
    return new Date(y, m - 1, d)
  }
  return new Date(config) // e.g. timestamp
}

执行这个函数时
因为你不能进入正则的判断只能 return new Date('20: 15')
但是new Date(config)的config是有要求的
你可以用Date.parse判断一下
Date.parse('20: 15') 返回 NaN就不能正常返回
Date.parse('2017:20: 15') 返回正常就可以返回

**Comment by iamkun** [comment]
I think maybe we shouldn't deal with those date parts or custom date string.
Cause if we wanna to cover all these situations, our library may become large as Moment.js. 

How do you think? Or any better idea?

**Comment by loo41** [comment]
I agree with this point of view. 
This library is mainly light weight
