### ISSUE TITLE
Constructor Issues with ISO 8601

### ISSUE THREAD

**Issue by BSprite** [xx45/dayjs#45]
> dayjs().format()
> "2018-04-24T11:21:29-07:00"
> dayjs("2018-04-24T11:21:23-07:00").format()
> "2018-04-24T11:21:23-07:00"
> dayjs("2018-04-24").format()
> "2018-04-23T17:00:00-07:00"
> dayjs("20180424").format()
> "2018-04-24T00:00:00-07:00"

It seems your regex isn't catching it properly.
A simple fix for just ISO formatted dates:

> if (/(\d{4}-\d{2}-\d{1,2})/.test(configStr)) {
>   //Date only
>   const date = regEx[1].split('-');
>   return new Date(date[0], date[1] - 1, date[2]);
> } else if (
>   /^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[01]|0[1-9]|[12][0-9])T(2[0-3]|[01][0-9]):([0-5][0-9]):([0-5][0-9])(.[0-9]+)?(Z)?$/.test(
>     configStr
>   )
> ) {
>   //Full 8601 String
>   return new Date(configStr);
> } else if (/(\d{4}-\d\d-\d\d)(.)(\d\d:\d\d)/.test(configStr)) {
>   //ISO Pattern: YYYY-MM-DD HH:mm
>   const regEx = /(\d{4}-\d\d-\d\d)(.)(\d\d:\d\d)/g.exec(configStr);
>   const date = regEx[1].split('-');
>   const time = regEx[3].split(':');
>   return new Date(date[0], date[1] - 1, date[2], time[0], time[1]);
> }

If you really want to be robust check out some of [Moment's constructor.](https://github.com/moment/moment/blob/develop/src/lib/create/from-string.js)

**Comment by iamkun** [comment]
thx, doing ...
