### ISSUE TITLE
startOf 不支持week 选项

### ISSUE THREAD

**Issue by tenbamboo** [xx45/dayjs#49]
dayjs().startOf('week').format('YYYY-MM-DD')
dayjs().endOf('week').format('YYYY-MM-DD')

**Comment by zhan8863** [comment]
自己写下吧！我也在用这个功能

**Comment by tenbamboo** [comment]
嗯，我在写。。。。

**Comment by tenbamboo** [comment]
我就不fork了，直接上代码：
```javascript
//本周
 let t = dayjs()
 let val1 = t.set('date', t.$D - t.$W).add(1, 'd').format('YYYY-MM-DD') //本周第一天（周一）
 let val2 = t.set('date', t.$D + (6 - t.$W)).add(1, 'd').format('YYYY-MM-DD')  //本周最后一天（周日）
//上周
 let t = dayjs().subtract(1, 'w')
 let val1 = t.set('date', t.$D - t.$W).add(1, 'd').format('YYYY-MM-DD') //上周第一天（周一）
 let val2 = t.set('date', t.$D + (6 - t.$W)).add(1, 'd').format('YYYY-MM-DD')  //上周最后一天（周日）
```

**Comment by iamkun** [comment]
thx, doing ...

**Comment by loo41** [comment]
case C.W:
        let $W = null
        if (this.$W === 0) {
          $W = 6
        } else if(this.$W === 1) {
          $W = 0
        } else {
          $W = this.$W - 1
        }
        if (isStartOf) {
          return new Dayjs(new Date(this.$y, this.$M, (this.$D - $W)))
        }
        return new Dayjs(new Date(this.$y, this.$M, this.$D + (6 - $W)))

// add  dayjs().startOf('week')  support，However,  the logic needs to be separated into good
