### ISSUE TITLE
Missing several format options

### ISSUE THREAD

**Issue by schiem** [xx45/dayjs#60]
The Moment [docs](https://momentjs.com/docs/#/parsing/string-format/) have a number of format options which are missing from DayJS.  Some of them, like the locality specific ones, I think it makes sense to exclude, but there are others that are missing that could be included without having a serious impact on the library size.

Here are the missing formats that I propose are added:

- Q  - Quarter of the year
- Do - Day of month with ordinal
- DDD/DDDD - Day of year
- X - Unix timestamp
- x - Unix timestamp with ms
- h/hh - 12 hour time
- k/kk - 24 hour time beginning at 1
- a/A - Post and ante meridiem
- S/SS/SSS - Milliseconds

However, this would nearly double the size of the format function, which isn't ideal.  Are there any of those that shouldn't be added?

**Comment by Frondor** [comment]
In my humble opinion, the only useful ones in that list are `h/hh` and `k/kk`. The rest doesn't look like human-friendly formats.

**Comment by schiem** [comment]
I would tend to agree, I think that Q, DDD/DDDD, X/x, and S/SS/SSS are definitely not necessary.   I think if h/hh is included, then a/A should probably be included as well, or you lose the ability to show specific times (1:00 vs 1:00 AM).

"Do" is kind of up in the air for me, because I've had clients who've insisted on having the ordinal (1st, 2nd, 3rd, etc) shown, but it's something that a user could implement on their own.  I think most of it comes down to "what should be provided by a library" vs. "what can a user be reasonably expected to write themselves," and I think that's mostly up to the owner of the repo.

**Comment by iamkun** [comment]
I tend to agree adding h/hh & a/A(with local). And leave the rest formats to a separate plugin, maybe called `AdvFormat`
It will be nice if we implement a plugin system like this.
```javascript
import { AdvFormat } from 'dayjs/plugin'
dayjs.extend('AdvFormat') // a plugin might add a new API or overwrite the existing one
//here it just overwrite the core.format
dayjs.format('Do SSS ... something less useful format')
```

**Comment by schiem** [comment]
I've updated #68 to only have AM/PM and 12 hour time support, with additional options included in another plugin (and the addition of a plugin system).

**Comment by schiem** [comment]
The PR from #68 has been split into #91 and #92.
