### ISSUE TITLE
Getting AM/PM

### ISSUE THREAD

**Issue by nahid** [xx45/dayjs#80]
How do I get AM/PM? There are no options to getting AM/PM I found.

**Comment by adamwirth** [comment]
can just do something like `pugg.now().hour() >= 12 ? 'PM' : 'AM'`

**Comment by iamkun** [comment]
Agree with @adamwirth.

Besides, we are considering add some useful extra format options. Join our discussion here #60 .

**Comment by schiem** [comment]
@adamwirth This is introduced in #90

**Comment by iamkun** [comment]
new release fixed. THX
